spring:
  application:
    name: springAI-alibaba-copilot
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-0090e14d131d4ef0b0b1d15a9eb95c69
      chat:
        options:
          model: qwen-turbo
  # Web配置
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: false
server:
  port: 8080

app:
  # 工作空间配置
  workspace:
    # 工作空间根目录路径
    root-directory: ${user.dir}/workspace
    max-file-size: 10485760  # 10MB
    allowed-extensions:
      - .txt
      - .md
      - .java
      - .js
      - .ts
      - .json
      - .xml
      - .yml
      - .yaml
      - .properties
      - .html
      - .css
      - .sql

  # 浏览器自动打开配置
  browser:
    # 是否启用自动打开浏览器
    auto-open: true
    # 自动打开的URL地址
    url: http://localhost:${server.port:8080}
    # 延迟打开时间
    delay-seconds: 2

  # 安全配置
  security:
    approval-mode: DEFAULT  # DEFAULT, AUTO_EDIT, YOLO
    dangerous-commands:
      - rm
      - del
      - format
      - fdisk
      - mkfs

  # 工具配置
  tools:
    read-file:
      enabled: true
      max-lines-per-read: 1000
    write-file:
      enabled: true
      backup-enabled: true
    edit-file:
      enabled: true
      diff-context-lines: 3
    list-directory:
      enabled: true
      max-depth: 5
    shell:
      enabled: true
      timeout-seconds: 30

logging:
  level:
    com.example.demo: DEBUG
    com.example.demo.tools: INFO
    com.example.demo.controller: INFO
    com.example.demo.service: INFO
    com.example.demo.config: DEBUG
    # 减少 Spring AI 工具调用相关的日志输出
    org.springframework.ai.model.tool.DefaultToolCallingManager: WARN
    org.springframework.ai.tool.method.MethodToolCallback: WARN
    org.springframework.ai: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/copilot-file-ops.log
